config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
    resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 4 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [ :new, :create ]

def new
  @bookmark = Bookmark.new
end

def create
  @bookmark = Bookmark.new(bookmark_params)
  @bookmark.list = @list
  if @bookmark.save
    redirect_to list_path(@list)
  else
    render template: "lists/show"
  end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
  @bookmark.destroy
  redirect_to root_path
end

private

def find_list
  @list = List.find(params[:list_id])
end

def bookmark_params
  params.require(:bookmark).permit(:comment, :movie_id)
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :imageUrl)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>All You Can Watch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="icon" type="image/png" href="https://images.unsplash.com/photo-1585842630354-c6766ebf210d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1100&q=80">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="fontawesome-stars.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="home-banner">
  <h1><span id="banner-typed-text"></span></h1>
    <h1 class="banner-arrow">⌵</h1>
</div>

<div class="container">
  <div class="row cards">
    <% @lists.each do |list| %>
      <div class="col-4-sm">
        <% if list.imageUrl.empty? %>
          <div class="card" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%), url('https://images.unsplash.com/photo-1534489573486-7d1fa4f436e4?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80')">
            <h3><%= link_to list.name, list_path(list)%></h3>
          </div>
        <% else %>
          <div class="card" style= "background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%), url('<%= list.imageUrl %>')">
          <h3><%= link_to list.name, list_path(list)%></h3>
        </div>
        <% end %>
        </div>
      <% end %>
    </div>
</div>

<%= javascript_pack_tag 'initTyped' %>

app/views/lists/new.html.erb
<div class="list-banner">
  <h1>Create your list</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, placeholder: 'Add a list name' %>
        <%= f.input :imageUrl, placeholder: 'Add an image URL' %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.imageUrl.empty? %>
    <div class="show-banner" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%), url('https://images.unsplash.com/photo-1534489573486-7d1fa4f436e4?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80')">
        <h3><%= @list.name %></h3>
    </div>
<% else %>
    <div class="show-banner" style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.12) 0, rgba(0,0,0,0.55) 74.4%),url('<%= @list.imageUrl %>')">
        <h2><%= @list.name %></h2>
    </div>
<% end %>

<button class="button-delete btn btn-danger">Delete the list</button>
<%= link_to "", list_path(@list), method: :delete, id: "delete-link", class: "hidden" %>

<div class="container">
  <div class="card-show-title">
    <h1>Movies 🎬</h1>
  </div>
    <div class="row cards-movie">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="col-6-sm">
          <div class="card-movie">
          <div class="card-poster">
              <%= image_tag bookmark.movie.poster_url, alt: "movie poster" %>
          </div>
          <div class="card-description">
            <div class="card-title">
              <h5><%= bookmark.movie.title %></h5>
              <p> <%= bookmark.movie.rating %> ⭐️</p>
            </div>
            <div class="card-overview">
              <p> <%= bookmark.movie.overview %> </p>
            </div>
            <hr>
              <p><strong>Review</strong></p>
            <div class="card-review">
              <p><%= bookmark.comment %></p>
            <button class="delete-movie btn btn-danger">Delete</button>
            <%= link_to "", bookmark_path(bookmark), method: :delete, id:"delete-bookmark", class: "hidden" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>

    <div class="row">
      <div class="col-12">
        <hr>
        <div class="form">
         <h3>Add a new movie</h3>
        <%= simple_form_for [ @list, @bookmark ] do |f| %>
          <%= f.input :comment, placeholder: 'Add your comment' %>
          <%= f.input :ratings, placeholder: 'Add your rating', collection: 1..5, id: "example"  %>
          <%= f.association :movie, input_html: { class: 'select2' } %>
          <%= f.submit "Add movie", class: "btn btn-primary" %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <h5 style="color: white">Made with ♥️ and 🧘🏻‍♀️</h5>
      <a class=social href="https://github.com/XiwayB" target="_blank">
        <i class="fab fa-github">
        </i>
      </a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-watchlist fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://images.unsplash.com/photo-1585842630354-c6766ebf210d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1100&q=80", class: "logo" %>
    <div class="btn navbar-btn">
      <%= link_to "Create a new list", new_list_path, class: "navbar-link" %>
    </div>
    <% end %>

  <div class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <div class="btn">
      <%= link_to new_list_path, class: "navbar-link" do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
</div>